"""add auth_user_id to user

Revision ID: 1a98601ae5d6
Revises: e88ae5e7b91b
Create Date: 2026-09-09 21:47:57.377933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a98601ae5d6'
down_revision: Union[str, Sequence[str], None] = 'e88ae5e7b91b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_auth_user_id'), 'users', ['auth_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_auth_user_id'), table_name='users')
    op.drop_column('users', 'auth_user_id')
    # ### end Alembic commands ###
